- name: Build java project
  hosts: build
  become: yes

  tasks:
    - name: Ensure packages installed
      apt:
        pkg:
          - git
          - default-jdk
          - maven
          - docker.io
          # - ansible-galaxy collection install community.docker
        state: present
        update_cache: true

    - name: Git clone
      git:
        repo: "https://github.com/kekcment/certification.git"
        dest: /tmp/certification
        clone: yes

    - name: Check war.file exists
      stat:
        path: /tmp/certification/target/hello-1.0.war
      register: result

    - name: Build Maven artifact
      command: mvn --batch-mode --quiet install
      args:
        chdir: /tmp/certification/
      when: not result.stat.exists

    # - name: Log into DockerHub
    #   community.docker.docker_login:
    #     username: docker
    #     password: rekcod

    # - name: Install ansible-galaxy collection
    #   shell: ansible-galaxy collection install community.docker

    # - name: Build image using cache source
    #   community.docker.docker_image:
    #     name: certification
    #     build:
    #     path: /tmp/certification
    #   source: build

    - name: Build image
      command: docker build -t certification -f /tmp/certification .

    - name: Tag and push to docker hub
      command: docker tag certification kekcment/certification:0.1.0 && docker push kekcment/certification:0.1.0
