- name: Production
  hosts: prod
  become: yes

  tasks:
  - name: Ensure docker installed
    apt:
     name: docker.io
     state: present

  - name: Pull an image
    community.docker.docker_image:
      name: kekcment/certification:0.1.0
      source: pull

  - name: Start a container
    docker_container:
      name: kekcment/certification:0.1.0
      state: started   