- name: Production
  hosts: prod
  become: yes

  tasks:
  - name: Ensure docker installed
    apt:
     name: docker.io
     state: present

  - name: Copy DockerHub login file 
    copy:
      src: /ya/docker_login.txt 
      dest: /tmp/

  - name: login on DockerHub
    shell: cat docker_login.txt | docker login --username kekcment --password-stdin
    args:
      chdir: /tmp/          

  - name: Pull an image & Start application
    shell: docker run -d -p 8080:8080 kekcment/certification:0.1.0

  # - name: Pull an image
  #   community.docker.docker_image:
  #     name: kekcment/certification:0.1.0
  #     source: pull

  # - name: Start a container
  #   docker_container:
  #     name: kekcment/certification:0.1.0
  #     state: started   