- name: Production
  hosts: prod
  become: yes

  tasks:
    - name: Ensure packages installed
      apt:
        pkg:
          - docker.io
          - python3-pip
        state: present
        update_cache: true

    - name: Install pip docker
      pip:
         name: docker 

    - name: Pull an image
      community.docker.docker_image:
        name: kekcment/certification:0.1.0
        source: pull

    - name: Start a container
      community.docker.docker_container:
        name: Production
        image: kekcment/certification:0.1.0
        state: started
        ports: "8080:8080"  