- name: Production
  hosts: prod
  become: yes

  tasks: 
  - name: Ensure tomcat9 package is present
    apt: 
      name: tomcat9
      state: present

  - name: Ensure default-jdk  package is present
    apt: 
      name: default-jdk
      state: present

  - name: Synchronize war.file
    synchronize:
      mode: push
      src: /tmp/certification/target/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/